"""initial schema

Revision ID: 68520bee23b2
Revises: 
Create Date: 2026-03-22 11:30:22.024491

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql
from pgvector.sqlalchemy import Vector

# revision identifiers, used by Alembic.
revision: str = '68520bee23b2'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute("CREATE EXTENSION IF NOT EXISTS vector")
    op.create_table('documents',
    sa.Column('title', sa.String(length=500), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('source', sa.String(length=500), nullable=True),
    sa.Column('doc_type', sa.String(length=50), nullable=False),
    sa.Column('embedding', Vector(1536), nullable=True),
    sa.Column('meta', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_documents_created_at'), 'documents', ['created_at'], unique=False)
    op.create_index(op.f('ix_documents_doc_type'), 'documents', ['doc_type'], unique=False)
    op.create_index(op.f('ix_documents_is_deleted'), 'documents', ['is_deleted'], unique=False)
    op.create_index('ix_documents_type', 'documents', ['doc_type'], unique=False)
    op.create_table('telegram_messages',
    sa.Column('chat_id', sa.String(length=100), nullable=False),
    sa.Column('message_id', sa.String(length=100), nullable=False),
    sa.Column('user_id', sa.String(length=100), nullable=False),
    sa.Column('username', sa.String(length=255), nullable=True),
    sa.Column('text', sa.Text(), nullable=False),
    sa.Column('processed', sa.Boolean(), nullable=False),
    sa.Column('workflow_run_id', sa.Uuid(), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_telegram_messages_chat_id'), 'telegram_messages', ['chat_id'], unique=False)
    op.create_index(op.f('ix_telegram_messages_created_at'), 'telegram_messages', ['created_at'], unique=False)
    op.create_index(op.f('ix_telegram_messages_is_deleted'), 'telegram_messages', ['is_deleted'], unique=False)
    op.create_index(op.f('ix_telegram_messages_processed'), 'telegram_messages', ['processed'], unique=False)
    op.create_index(op.f('ix_telegram_messages_user_id'), 'telegram_messages', ['user_id'], unique=False)
    op.create_index('ix_telegram_unprocessed', 'telegram_messages', ['processed', 'created_at'], unique=False)
    op.create_table('workflow_runs',
    sa.Column('workflow_name', sa.String(length=100), nullable=False),
    sa.Column('task_id', sa.Uuid(), nullable=False),
    sa.Column('celery_task_id', sa.String(length=255), nullable=True),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('input_data', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('output_data', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('errors', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('completed_nodes', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('trace_id', sa.String(length=255), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_workflow_runs_created', 'workflow_runs', ['created_at'], unique=False)
    op.create_index(op.f('ix_workflow_runs_created_at'), 'workflow_runs', ['created_at'], unique=False)
    op.create_index(op.f('ix_workflow_runs_is_deleted'), 'workflow_runs', ['is_deleted'], unique=False)
    op.create_index('ix_workflow_runs_name_status', 'workflow_runs', ['workflow_name', 'status'], unique=False)
    op.create_index(op.f('ix_workflow_runs_status'), 'workflow_runs', ['status'], unique=False)
    op.create_index(op.f('ix_workflow_runs_task_id'), 'workflow_runs', ['task_id'], unique=False)
    op.create_index(op.f('ix_workflow_runs_workflow_name'), 'workflow_runs', ['workflow_name'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute("DROP EXTENSION IF EXISTS vector")
    op.drop_index(op.f('ix_workflow_runs_workflow_name'), table_name='workflow_runs')
    op.drop_index(op.f('ix_workflow_runs_task_id'), table_name='workflow_runs')
    op.drop_index(op.f('ix_workflow_runs_status'), table_name='workflow_runs')
    op.drop_index('ix_workflow_runs_name_status', table_name='workflow_runs')
    op.drop_index(op.f('ix_workflow_runs_is_deleted'), table_name='workflow_runs')
    op.drop_index(op.f('ix_workflow_runs_created_at'), table_name='workflow_runs')
    op.drop_index('ix_workflow_runs_created', table_name='workflow_runs')
    op.drop_table('workflow_runs')
    op.drop_index('ix_telegram_unprocessed', table_name='telegram_messages')
    op.drop_index(op.f('ix_telegram_messages_user_id'), table_name='telegram_messages')
    op.drop_index(op.f('ix_telegram_messages_processed'), table_name='telegram_messages')
    op.drop_index(op.f('ix_telegram_messages_is_deleted'), table_name='telegram_messages')
    op.drop_index(op.f('ix_telegram_messages_created_at'), table_name='telegram_messages')
    op.drop_index(op.f('ix_telegram_messages_chat_id'), table_name='telegram_messages')
    op.drop_table('telegram_messages')
    op.drop_index('ix_documents_type', table_name='documents')
    op.drop_index(op.f('ix_documents_is_deleted'), table_name='documents')
    op.drop_index(op.f('ix_documents_doc_type'), table_name='documents')
    op.drop_index(op.f('ix_documents_created_at'), table_name='documents')
    op.drop_table('documents')
    # ### end Alembic commands ###
