"""add conversation memory

Revision ID: ed8d608be5e2
Revises: 68520bee23b2
Create Date: 2026-03-22 19:33:22.842179

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ed8d608be5e2'
down_revision: Union[str, Sequence[str], None] = '68520bee23b2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('conversation_memory',
    sa.Column('chat_id', sa.String(length=100), nullable=False),
    sa.Column('role', sa.String(length=20), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('workflow_name', sa.String(length=100), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_conversation_memory_chat_id'), 'conversation_memory', ['chat_id'], unique=False)
    op.create_index(op.f('ix_conversation_memory_created_at'), 'conversation_memory', ['created_at'], unique=False)
    op.create_index(op.f('ix_conversation_memory_is_deleted'), 'conversation_memory', ['is_deleted'], unique=False)
    op.create_index('ix_memory_chat_created', 'conversation_memory', ['chat_id', 'created_at'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_memory_chat_created', table_name='conversation_memory')
    op.drop_index(op.f('ix_conversation_memory_is_deleted'), table_name='conversation_memory')
    op.drop_index(op.f('ix_conversation_memory_created_at'), table_name='conversation_memory')
    op.drop_index(op.f('ix_conversation_memory_chat_id'), table_name='conversation_memory')
    op.drop_table('conversation_memory')
    # ### end Alembic commands ###
